server:
  port: 9060


security:
  oauth2:
    # 认证信息
    client:
      client-id: orderService
      client-secret: 123456
    # 启动服务器时去获取JWT token key
    resource:
      jwt:
        key-uri: http://auth.itihub.com:9090/oauth/token_key

spring:
  application:
    name: orderApi
  cloud:
    sentinel:
      transport:
        port: 8719                      # sentinel 与dashboard通讯端口
        dashboard: localhost:8080       # dashboard 地址
