version: "3.7"

services:

  is-order-api:
    build: ./is-order-api
    image: jizhe/is-order-api
    environment:
      - ORDER_SENTINEL_PORT
      - ORDER_DASHBOARD
      - ORDER_OAUTH_CLIENT_ID
      - ORDER_OAUTH_CLIENT_SECRET
      - ORDER_OAUTH_RESOURCE_JWT_KEY_URI
      - ORDER_ZOOKEEPER_ADDRESS
      - ORDER_ZOOKEEPER_PATH
    networks:
      - internal_access

  is-price-api:
    build: ./is-price-api
    image: jizhe/is-price-api
    environment:
      - PRICE_OAUTH_CLIENT_ID
      - PRICE_OAUTH_CLIENT_SECRET
      - PRICE_OAUTH_RESOURCE_JWT_KEY_URI

  is-server-auth:
    build: ./is-server-auth
    image: jizhe/is-server-auth
    environment:
      - AUTH_DATASOURCE_URL
      - AUTH_DATASOURCE_USERNAME
      - AUTH_DATASOURCE_PASSWORD
      - AUTH_REDIS_HOST
      - AUTH_REDIS_PORT
    networks:
      - internal_access

  is-server-gateway:
    build: ./is-server-gateway
    image: jizhe/is-server-gateway
    environment:
      - USER_SERVER_URL
      - AUTH_SERVER_URL
      - ORDER_SERVER_URL
      - GATEWAY_DATASOURCE_URL
      - GATEWAY_DATASOURCE_USERNAME
      - GATEWAY_DATASOURCE_PASSWORD
      - GATEWAY_OAUTH_CLIENT_ID
      - GATEWAY_OAUTH_CLIENT_SECRET
      - GATEWAY_OAUTH_RESOURCE_JWT_KEY_URI
    networks:
      - internal_access


networks:
  internal_access:
    internal: true