
spring:
  datasource:
    url: jdbc:mysql://local.docker.node1.com:3306/security?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: local.docker.node1.com
    port: 6379