
spring:
  datasource:
    url: jdbc:mysql://local.docker.node1.com:3306/security?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: local.docker.node1.com
    port: 6379

security:
  oauth2:
    store-type: jwt    # jwt / redis（默认）
    client:
      store-type: redis  # 不配置默认使用JDBC
