server:
  port: 9090
  servlet:
    session:
      timeout: 2592000

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://local.docker.node1.com:3306/security?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver